slam_toolbox:
  ros__parameters:
    # Frame names
    odom_frame: odom
    map_frame: map
    base_frame: base_link
    scan_topic: /scan

    # Common Settings
    use_sim_time: true
    mode: mapping

    # Solver settings (defaults)
    solver_plugin: solver_plugins::CeresSolver
    ceres_linear_solver: SPARSE_NORMAL_CHOLESKY
    ceres_preconditioner: JACOBI
    ceres_trust_strategy: LEVENBERG_MARQUARDT
    ceres_dogleg_type: TRADITIONAL_DOGLEG
    ceres_loss_function: None